### ISSUE TITLE
update not behaving as expected

### ISSUE THREAD

**Issue by dbvisel** [craftcms/gatsby-helper#11]
### Description

Since Gatsby Helper 1.0.0 was released, it appears in Updates; if I update it, it appears to install correctly, though when I go back to Updates, it's still there. Now it's there with 1.0.1. I don't think the problem is on my end – I just updated Craft without any problem – though I'm willing to believe that might be the case. Any ideas?

I don't want to uninstall the plugin and reinstall it because I worry I would lose my schema. Is that what I should try?

Thanks!

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

Gatsby Helper 1.0.0-beta.2
nethooks 1.1.2
Redactor 2.8.5
Webhooks 2.3.2

**Comment by andris-sevcenko** [comment]
We did release 1.0.1 yesterday, though. Are you saying that after updating to it, it still shows up in the updates?

So, if you update, it never really updates? Can you check the version in Settings -> Plugins?

**Comment by dbvisel** [comment]
Thanks. That's what happens – I can't figure this out. If I go to my Craft updates dashboard, this is what I see: 

<img width="1076" alt="Screen Shot 2021-03-31 at 5 06 10 PM" src="https://user-images.githubusercontent.com/3360195/113119903-8a8ea380-9243-11eb-9554-ef1c9b8a8e89.png">

(note that it's both of 'em). I click "Update" it grinds away, updating Composer dependencies, and ends up with a cheerful  All done! But then I'm back on the updates screen and it shows exactly the same thing.

The installed Gatsby Helper in Utilities > System Report is 1.0.0-beta.2;

**Comment by brandonkelly** [comment]
@dbvisel Open `vendor/craftcms/gatsby-helper/composer.json`. What does the `version` say in there?

Then open `vendor/craftcms/plugins.php` and search for `'craftcms/gatsby-helper' =>`. What does the `version` in the following array say?

**Comment by dbvisel** [comment]
In vendor/craftcms/gatsby-helper/composer.json: "version": "1.0.1"

In vendor/craftcms/plugins.php: 'version' => '1.0.0-beta.2',

**Comment by brandonkelly** [comment]
@dbvisel So the update did in fact get pulled in, but for some reason Craft’s Composer extension never found out about it. Or perhaps there’s a permissions issue with `vendor/craftcms/plugins.php`.

Try nuking your `vendor/` folder, and then run `composer install`.

**Comment by dbvisel** [comment]
I did that and it's working perfectly now. Thanks so much for your help, @brandonkelly and @andris-sevcenko !
