### ISSUE TITLE
Updating to 1.0.6 breaks incremental builds

### ISSUE THREAD

**Issue by emson-digital** [craftcms/gatsby-helper#16]
### Description
As stated in the title. Gatsby is no longer seeing updated content in the new update. Reverting to 1.0.5 resolves this.

### Steps to reproduce

1. Make edit in CMS
2. Gatsby doesn't see any changes

1.0.6
![image](https://user-images.githubusercontent.com/80485500/137965201-ba2fb2bf-3934-44da-bbf3-f9ba5ff40600.png)

1.0.5
![image](https://user-images.githubusercontent.com/80485500/137965239-f449eeb9-54f2-4e31-802e-926b3a3cc55f.png)

### Additional info

- Craft version: 3.7.16
- PHP version: 8.1
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Is this on a multisite build?

**Comment by emson-digital** [comment]
Yes, though only one site has entries assigned to it currently.

**Comment by andris-sevcenko** [comment]
Is that site the primary site? Also, have you set the `enabledSites` setting to anything for the `gatsby-source-craft` plugin?

**Comment by emson-digital** [comment]
Yes, it is the primary site, have not set enabled sites in the gatsby source plugin.

**Comment by emson-digital** [comment]
I notice today that there is a new gatsby-source-craft plugin that requires 1.0.6 that plugin was not updated after updating the CMS helper. I don't know if there was anything explicitly stated on 1.0.6 that made us aware of the Gatsby plugin update. I can assume that now that I see that, I will need to update the plugin in Gatsby for these to work together as expected? I will update both of these today sometime and get back to you.

**Comment by andris-sevcenko** [comment]
Sorry, I didn't get around to it today. Theoretically, if you have not set the enabled sites, everything on the primary site should still have been sourced. I'll figure this out tomorrow and will also get back to you!

**Comment by andris-sevcenko** [comment]
Found the bug, working on it!

**Comment by andris-sevcenko** [comment]
Alright, just cut the 1.0.7 release that should fix this!
