### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by vanburenx** [craftcms/gatsby-helper#17]
### Description

Deprecation Warning for Gatsby Helper plugin:

**Message** Elements’ `getSourceId()` method has been deprecated. Use `getCanonicalId()` instead.
**Origin**: `/app/vendor/craftcms/gatsby-helper/src/Plugin.php:210`

**Craft CMS Reference**: Returns the element’s canonical ID.
[https://github.com/craftcms/cms/blob/develop/src/base/Element.php#L2314](https://github.com/craftcms/cms/blob/develop/src/base/Element.php#L2314)

### Steps to reproduce

1. Install Gatsby Helper Plugin
2. Add a Preview Webhook URL in the Plugin Settings
3. Navigate to an entry in the Craft CP.
4. Navigate away from that entry.
5. Deprecation Warning triggered.

### Additional info

- Craft version: Craft Pro 3.7.20
- PHP version: 7.4.24
- Database driver & version: PostgreSQL 13.3
- Plugins & versions: Gatsby Helper 1.0.7

**Comment by andris-sevcenko** [comment]
Thanks for the heads up! Just fixed this and cut a 1.0.8 release.
