### ISSUE TITLE
Preview URLs without a port defined will fail

### ISSUE THREAD

**Issue by monachilada** [craftcms/gatsby-helper#4]
Referencing this line: https://github.com/craftcms/gatsby-helper/blob/a7febe59a99ef0e13f5bc2c1a9a69f641cf3ff53/src/Plugin.php#L162

If I supply a preview URL that doesn't have a port number — meaning I'm assuming port 80 as the default — then this check will fail.

**Comment by alexhillel** [comment]
I think there is also a mis-match in logic here with the code in line 176:

`if ((doPreview || currentlyPreviewing) && (!doPreview || ("$compare" == compareUrl.protocol + '//' + compareUrl.host))) {`

I think that there is no way for this to match if the port is included in the `$compare` string in line 162.

**Comment by brandonkelly** [comment]
Gatsby Helper 1.0.0-beta.2 is out now with a fix for this.
