### ISSUE TITLE
Previewing with Gatsby cloud is not possible.

### ISSUE THREAD

**Issue by monachilada** [craftcms/gatsby-helper#5]
Live preview with a self managed development instance works great with the plugin so long as the `ENABLE_GATSBY_REFRESH_ENDPOINT` .env variable is enabled and the preview URL matches what's been set in the plugin settings.

However, Gatsby Cloud's Preview service works slightly differently. Instead of exposing the `__refresh` URL to trigger a rebuild of a development site, they instead expect a post request to a randomly generated webhook. This is running on a different domain and so the comparison referenced in the code below will fail.

https://github.com/craftcms/gatsby-helper/blob/a7febe59a99ef0e13f5bc2c1a9a69f641cf3ff53/src/Plugin.php#L176

Since there is no apparent relation between the webhook URL and the preview URL, there would need to be some other way to identify which preview URL belongs to which webhook. For illustration purposes, a webhook and preview URL might look like this:

URL: `https://preview-PROJECT-SLUG.gtsb.io/`
Webhook: `https://webhook.gatsbyjs.com/hooks/data_source/RANDOM-STRING`

Secondly, the webhook doesn't expect `__refresh` to be appended to the URL, so this code will generate an invalid URL to send the post hook too.

https://github.com/craftcms/gatsby-helper/blob/a7febe59a99ef0e13f5bc2c1a9a69f641cf3ff53/src/Plugin.php#L166

**Comment by andris-sevcenko** [comment]
Yeah, I'm on it.

**Comment by andris-sevcenko** [comment]
I've fixed the whole `__refresh` saga, however, Live Preview still won't correctly work on Gatsby Cloud. It appears, there's some backend engineering that still needs to be in place. We're working on it :)

**Comment by andris-sevcenko** [comment]
With the next release of this plugin (soon!) the Gatsby Cloud previews should work.

Going forward, the freshly renamed `webhookTarget` setting should be the entire webhook target, whether it ends in `__refresh` or whether it's a Gatsby Cloud webhook. No more guessing by this plugin.

**Comment by brandonkelly** [comment]
Gatsby Helper 1.0.0-beta.2 is out now with this change.

**Comment by sandren** [comment]
It's working! 😍
