### ISSUE TITLE
Gatsby complains about missing "sourceID" when saving content without previewing

### ISSUE THREAD

**Issue by ken-gladeye** [craftcms/gatsby-helper#6]
### Description

I have Live Preview setup with a local Gatsby development as per instruction [here](https://github.com/craftcms/gatsby-source-craft#for-local-development)

When editing an entry and hit Cmd+S, my local Gatsby displays the following error

```
"gatsby-source-craft" threw an error while running the sourceNodes lifecycle:

Value of the ID field "sourceId" can't be nullish. Got object with keys:
remoteTypeName, remoteId
```

Digging a bit deeper, it seems to me that the `alertGatsby` function in [Plugin.php](https://github.com/craftcms/gatsby-helper/blob/main/src/Plugin.php#L159) does trigger on save but does not send the required element id. Making the following edit seems to resolve the error to me.

![Screen Shot 2021-02-04 at 13 55 45](https://user-images.githubusercontent.com/65751307/106829457-09a6a600-66f1-11eb-879b-3b0c32db5d16.png)

Happy to do a pull request if you think it's the root cause of the issue.

### Steps to reproduce

1. Install and setup Gatsby Live Preview
2. Edit an entry then hit Cmd+S

### Additional info

- Craft version: Craft Pro 3.6.2
- PHP version: 7.3.26
- Database driver & version: MySQL 5.7.28
- Plugins & versions: 1.0.0-beta.2

**Comment by andris-sevcenko** [comment]
Is this during live preview or just editing and saving?

**Comment by ken-gladeye** [comment]
Just when editing and saving the entry not during live preview

**Comment by andris-sevcenko** [comment]
@ken-gladeye go it, going to look into this!

**Comment by andris-sevcenko** [comment]
Alright, pushed a fix to the develop branch for this.

Have to implement #7 and should be good for another release. I plan to do that this week!

**Comment by ken-gladeye** [comment]
awesome thanks @andris-sevcenko!
