### ISSUE TITLE
Trigger a site build on element save

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/gatsby-helper#7]
### Description

It would be extremely useful if there was an option to trigger a site build on element save.

**Comment by mattstein** [comment]
FWIW @andris-sevcenko: https://github.com/workingconcept/trigger-craft-plugin

**Comment by ken-gladeye** [comment]
looking forward to this, would be a massive improvement to the editing / previewing experience with Gatsby site

**Comment by andris-sevcenko** [comment]
Just pushed this to the `develop` branch. Will cut a release today.

**Comment by ken-gladeye** [comment]
🎉
